apiVersion: v1
kind: Service
metadata:
  name: xld-service
  labels:
    app: xlrelease
    release: 8.2.0
spec:
  type: LoadBalancer
  ports:
    - port: 5516
      targetPort: xlr-http
      protocol: TCP
      name: xlr-http-svc
  selector:
    app: xlrelease
    release: 8.2.0