apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xlr-pv-claim-repository
  labels:
    app: xldeploy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
